version: 2
updates:
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: monthly
    - package-ecosystem: 'maven'
      directory: '/'
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
      ignore:
          # Freeze production dependencies of mcp-core
          - dependency-name: 'org.slf4j:slf4j-api'
          - dependency-name: 'com.fasterxml.jackson.core:jackson-annotations'
          - dependency-name: 'tools.jackson.core:jackson-databind'
          - dependency-name: 'io.projectreactor:reactor-bom'
          - dependency-name: 'io.projectreactor:reactor-core'
          - dependency-name: 'jakarta.servlet:jakarta.servlet-api'
          # mcp-json-jackson2 and mcp-json-jackson3 dependencies
          - dependency-name: 'com.fasterxml.jackson.core:jackson-databind'
          - dependency-name: 'com.networknt:json-schema-validator'